[build]
  base = "Frontend_React"
  publish = "dist"
  command = "npm ci && npm run build"

# SPA rewrite cho react-router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build.environment]
  NODE_VERSION = "20"
